import os
os.system('python gen_tasks.py')
from adversarialML.biologically_inspired_models.src.imagenet100_adam_linear_warmup_decay_tasks import *
from adversarialML.biologically_inspired_models.src.imagenet100_retina_blur_adam_linear_warmup_decay_tasks import *
from adversarialML.biologically_inspired_models.src.imagenet100_retina_nonuniform_patch_adam_linear_warmup_decay_tasks import *
from adversarialML.biologically_inspired_models.src.imagenet100_32x32_adam_linear_warmup_decay_tasks import *
from adversarialML.biologically_inspired_models.src.imagenet100_32x32_retina_blur_adam_linear_warmup_decay_tasks import *
from adversarialML.biologically_inspired_models.src.imagenet75_32x32_adam_linear_warmup_decay_tasks import *
from adversarialML.biologically_inspired_models.src.imagenet75_32x32_retina_blur_adam_linear_warmup_decay_tasks import *